### ISSUE TITLE
Golf.txt

### ISSUE THREAD

**Issue by JKerb** [Java2Class/minigolf#3]
Stupid Putt Putt
1691 Stupid Rd
Tampa, FL 33613
1,2
2,3
3,5
4,2
5,4
6,3
7,1
8,2
9,4
10,5
11,2
12,3
13,4
14,5
15,2
16,1
17,3
18,4

**Comment by JSilvey** [comment]
lol

**Comment by JSilvey** [comment]
I just added the file to the project. pull the new version
